### ISSUE TITLE
How to run project

### ISSUE THREAD

**Issue by KuugaYuuto** [AlpetGexha/Laravel-Asset-Management#9]
Hello I can't run project can you help me please and if you have video tutorial that would be great!

**Comment by AlpetGexha** [comment]
> Hello I can't run project can you help me please and if you have video tutorial that would be great!

Just run those command 

```
git clone https://github.com/AlpetGexha/Laravel-Asset-Management.git
cd Laravel-Asset-Management
composer install
cp .env.example .env
php artisan migrate --seed
```
press yes if they ask for to create a database
if not make the one from database manual

and then start the server 
```
php artisan serve
```

and u all good to go
